test15

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,10 +15,33 @@ jobs:
       idf_version: v5.5.1
       target: esp32
       bin: build/*.bin
+      hardware: ~
+      version: ~
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+
+      - name: Get hardware and version from CMakeLists.txt
+        run: |
+          hardware=$(grep -oP 'add_compile_definitions\s*\(\s*hardware\s*=\s*"\K[^"]+' CMakeLists.txt)
+          version=$(grep -oP 'project\s*\([^)]*VERSION\s+\K[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt)
+
+          if [ -z "$hardware" ]; then
+            echo "Hardware not found in CMakeLists.txt"
+            exit 1
+          fi
+
+          echo "Detected hardware: $hardware"
+          echo "hardware=$hardware" >> $GITHUB_ENV
+
+          if [ "v$version" != "${{github.ref_name}}" ]; then
+            echo "Version mismatch!\nv$version != ${{github.ref_name}}"
+            exit 1
+          fi
+
+          echo "Detected version: $version"
+          echo "version=$version" >> $GITHUB_ENV
 
       - name: Build with ESP-IDF
         uses: espressif/esp-idf-ci-action@v1
@@ -52,17 +75,3 @@ jobs:
           tag_name: ${{github.ref_name}}
           files: |
             ${{ env.bin }}
-
-      - name: Get hardware from CMakeLists.txt
-        env:
-          hardware: ~
-        run: |
-          hardware=$(grep -oP 'add_compile_definitions\s*\(\s*hardware\s*=\s*"\K[^"]+' CMakeLists.txt)
-
-          if [-z "$hardware"]; then
-            echo "Hardware not found in CMakeLists.txt"
-            exit 1
-          fi
-
-          echo "Detected hardware: $hardware"
-          echo "hardware=$hardware" >> $GITHUB_ENV
