test24

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,8 +24,7 @@ jobs:
 
       - name: Get hardware and version from CMakeLists.txt
         run: |
-          hardware=$(grep -oP 'add_compile_definitions\s*\(\s*hardware\s*=\s*"\K[^"]+' CMakeLists.txt)
-          version=$(grep -oP 'project\s*\([^)]*VERSION\s+\K[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt)
+          hardware=$(grep -oP 'hardware\s*=\s*"\K[^"]+' CMakeLists.txt)
 
           if [ -z "$hardware" ]; then
             echo "Hardware not found in CMakeLists.txt"
@@ -35,15 +34,6 @@ jobs:
           echo "Detected hardware: $hardware"
           echo "hardware=$hardware" >> $GITHUB_ENV
 
-          if [ "v$version" != "${{github.ref_name}}" ]; then
-            echo "Version mismatch!\nv$version != ${{github.ref_name}}"
-
-            exit 1
-          fi
-
-          echo "Detected version: $version"
-          echo "version=$version" >> $GITHUB_ENV
-
       - name: Build with ESP-IDF
         uses: espressif/esp-idf-ci-action@v1
         with:
@@ -52,16 +42,29 @@ jobs:
           path: '.'
           command: |
             idf.py build
-
-      - name: Get firmware binary
+      
+      - name: Get Project Description and firmware binary file
+        env:
+          json: build/project_description.json
         run: |
-          bin=$(ls ${{env.bin}} \
-          | grep -v bootloader \
-          | grep -v partition \
-          | grep -v ota_data \
-          | head -n 1)
+          version=$(jq -r '.project_version' ${{env.json}})
+          if [ "v$version" != "${{github.ref_name}}" ]; then
+            echo "Version mismatch!\nv$version != ${{github.ref_name}}"
 
+            exit 1
+          fi
+          
+          build=build/$(jq -r '.app_bin' ${{env.json}})
+          bin=firmwares/${{env.hardware}}.bin
+          mv -f $build $bin
           echo "bin=$bin" >> $GITHUB_ENV
+
+      #   bin=$(ls ${{env.bin}} \
+      #   | grep -v bootloader \
+      #   | grep -v partition \
+      #   | grep -v ota_data \
+      #   | head -n 1)
+      #   echo "bin=$bin" >> $GITHUB_ENV
 
       # - name: Upload build artifacts
       #   uses: actions/upload-artifact@v4
@@ -70,25 +73,25 @@ jobs:
       #     path: |
       #       ${{env.bin}}
 
-      - name: Update manifest file
-        run: |
-          sha=$(sha256sum build/Git_OTA.bin | awk '{print $1}')
+      # - name: Update manifest file
+      #   run: |
+      #     sha=$(sha256sum build/Git_OTA.bin | awk '{print $1}')
 
-          jq \
-            --arg hw "${{env.hardware}}" \
-            --arg ver "${{env.version}}" \
-            --arg sha "$sha" \
-            '.[$hw].version = $ver | .[$hw].sha256 = $sha' \
-            manifest.json > manifest.json
+      #     jq \
+      #       --arg hw "${{env.hardware}}" \
+      #       --arg ver "${{env.version}}" \
+      #       --arg sha "$sha" \
+      #       '.[$hw].version = $ver | .[$hw].sha256 = $sha' \
+      #       manifest.json > manifest.tmp
           
-        #   mv manifest.tmp manifest.json
+      #     mv manifest.tmp manifest.json
 
-      - name: Commit changes to manifest file
+      - name: Commit and push changes
         run: |
           git config user.name "github-actions"
           git config user.email "actions@github.com"
-          git add manifest.json
-          git commit -m "Update manifest for ${{env.hardware}} (${{env.version}})" || echo "Nothing to commit"
+          git add firmwares
+          git commit -m "Update firmware for ${{env.hardware}} (${{env.version}})" || echo "Nothing to commit"
           git push origin HEAD:main
 
       - name: Create GitHub Release with firmware
@@ -98,10 +101,10 @@ jobs:
           files: |
             ${{env.bin}}
       
-      - name: Delete tag on failure
+      - name: Delete the tag and release, on failure
         if: failure()
         env:
           GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
         run: |
-          git push origin ":refs/tags/${{github.ref_name}}" || true
-          gh release delete "${{github.ref_name}}" --yes || true
+          git push origin ":refs/tags/${{github.ref_name}}" || echo "Could not delete tag"
+          gh release delete "${{github.ref_name}}" --yes || echo "Cant find release to delete"
